from playwright.sync_api import sync_playwright
from pathlib import Path
from asset_routes import install_asset_routes
import json,time
W=Path(__file__).resolve().parent.parent
results=[]
def check(name,condition,details=None):
 assert condition,(name,details)
 results.append({'test':name,'passed':True,'details':details})
with sync_playwright() as pw:
 browser=pw.chromium.launch(headless=True,args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':1448,'height':1250})
 install_asset_routes(page)
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto('http://127.0.0.1:4177/index.html',wait_until='networkidle');page.evaluate('dashboard.ready')
 get=lambda:page.evaluate('dashboard.getState()')
 page.locator('#reset').click();s=get()
 check('initial wide ribbons match telemetry',page.evaluate('dashboard.getBands()')=={'speed':.64,'rpm':.7})
 check('reference values',s['speed']==128 and s['gear']==4 and s['rpm']==5600 and abs(s['range']-310)<.03 and s['coolant']==198,s)
 page.locator('#accelerate').focus();page.keyboard.down('Space');page.wait_for_timeout(600);page.keyboard.up('Space');s=get()
 check('held keyboard pedal accelerates',s['speed']>134 and s['rpm']>5800,s)
 speed=s['speed'];page.locator('#upshift').click();page.wait_for_timeout(600);s=get()
 live=page.evaluate('({state:dashboard.getState(),bands:dashboard.getBands()})')
 check('wide ribbons follow live throttle and RPM',abs(live['bands']['speed']-live['state']['speed']/200)<1e-9 and abs(live['bands']['rpm']-live['state']['rpm']/8000)<1e-9,live)
 check('upshift preserves speed and decreases RPM',s['gear']==5 and abs(s['speed']-speed)<.2 and s['rpm']<4800,s)
 check('valid downshift remains available',not page.locator('#downshift').is_disabled())
 page.keyboard.down('ArrowDown');page.wait_for_timeout(800);page.keyboard.up('ArrowDown');s=get()
 check('brake lowers road and engine speeds',s['speed']<speed-20 and s['rpm']<4200,s)
 check('range falls slowly and coolant bounded',309<s['range']<310 and 198<=s['coolant']<=206,s)
 page.locator('#pause').click();paused=get();page.wait_for_timeout(300)
 pausedBands=page.evaluate('dashboard.getBands()');page.wait_for_timeout(120)
 check('pause freezes both wide ribbons',page.evaluate('dashboard.getBands()')==pausedBands,pausedBands)
 check('pause freezes all telemetry',get()==paused,paused)
 check('pause exposes Resume and disables pedals',page.locator('#pause').inner_text()=='Resume' and page.locator('#accelerate').is_disabled())
 page.locator('#pause').click();page.locator('#reset').click()
 check('reset restores wide ribbon fractions',page.evaluate('dashboard.getBands()')=={'speed':.64,'rpm':.7})
 page.keyboard.down('ArrowDown');page.wait_for_timeout(1200);page.keyboard.up('ArrowDown');page.locator('#downshift').click();s=get()
 check('valid downshift at lower speed',s['gear']==3,s)
 check('unsafe second downshift disabled',page.locator('#downshift').is_disabled(),s)
 page.locator('#reset').click();page.locator('#upshift').click();page.locator('#upshift').click()
 check('upper gear boundary',get()['gear']==6 and page.locator('#upshift').is_disabled(),get())
 page.locator('#reset').click();page.locator('#demo').click();page.wait_for_timeout(1400)
 check('demo starts from reference and accelerates',get()['speed']>130,get())
 page.keyboard.down('ArrowDown');page.wait_for_timeout(100);page.keyboard.up('ArrowDown')
 check('manual input cancels scripted demo',page.locator('#demo').get_attribute('aria-pressed')=='false',get())
 page.locator('#reset').click();page.keyboard.down('ArrowUp');page.wait_for_timeout(150)
 page.evaluate("window.dispatchEvent(new Event('blur'))");page.keyboard.up('ArrowUp');a=get()['speed'];page.wait_for_timeout(250)
 check('focus loss releases pedal',abs(get()['speed']-a)<.25,get())
 page.locator('#reset').click();page.locator('#accelerate').focus();page.keyboard.down('ArrowUp');page.wait_for_timeout(100);page.locator('#pause').focus();a=get()['speed'];page.wait_for_timeout(250);check('global key ownership survives button focus change',get()['speed']>a+2,get());page.keyboard.up('ArrowUp')
 page.locator('#reset').click();box=page.locator('#accelerate').bounding_box();page.mouse.move(box['x']+20,box['y']+20);page.mouse.down();page.wait_for_timeout(350);page.mouse.move(0,0);page.mouse.up();a=get()['speed'];page.wait_for_timeout(200)
 check('pointer capture releases outside button',a>130 and abs(get()['speed']-a)<.3,get())
 for width,height in [(390,844),(768,1024),(1448,1086)]:
  page.set_viewport_size({'width':width,'height':height});page.wait_for_timeout(100)
  metrics=page.evaluate("({width:innerWidth,scroll:document.documentElement.scrollWidth,ratio:document.querySelector('#viewport').getBoundingClientRect().width/document.querySelector('#viewport').getBoundingClientRect().height,minTarget:Math.min(...[...document.querySelectorAll('button')].map(x=>x.getBoundingClientRect().height))})")
  check('responsive '+str(width),metrics['scroll']<=width+1 and abs(metrics['ratio']-1448/1086)<.002 and metrics['minTarget']>=44,metrics)
 page.emulate_media(reduced_motion='reduce');page.locator('#reset').click();page.keyboard.down('ArrowDown');page.wait_for_timeout(200);page.keyboard.up('ArrowDown')
 check('reduced motion retains functionality',get()['speed']<128,get())
 check('no browser errors',not errors,errors)
 browser.close()
(W/'interaction-checks.json').write_text(json.dumps(results,indent=2)+'\n')
print(json.dumps({'passed':len(results),'tests':[r['test'] for r in results]}))
